# Generated by Django 3.1.5 on 2021-01-05 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('investorsmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 5, 15, 10, 45, 992108, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
