# Generated by Django 3.1.5 on 2021-01-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investorsmanager', '0002_investor_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='website_url',
            field=models.CharField(default='NO EMAIl', max_length=200),
        ),
    ]
