# Generated by Django 3.1.5 on 2021-01-10 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investorsmanager', '0003_investor_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investors', to=settings.AUTH_USER_MODEL),
        ),
    ]
